apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website
  labels:
    app: portfolio-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
        - name: portfolio-website
          image: anubharani/personal-portfolio-website:latest
          ports:
            - containerPort: 80